// s14 — inscription d'organisation (C) et création d'évènement en 3 étapes (E) : rattachement vérifié côté serveur,
// organisation non approuvée refusée, code Bizouk malveillant rejeté (rien n'est stocké), pièces réservées aux admins, parcours navigateur (Playwright).
import { chromium } from 'playwright';
import * as L from './lib.mjs';
const { ok, section, as, q, one, USERS } = L;

await L.resetDb();
await q(`truncate public.organizer_documents, public.organizer_applications, public.organizer_members, public.event_sessions, public.event_details cascade`);
await q(`delete from public.organizers where not is_default`);
const A = (await one(`insert into public.organizers (name, account_status, siret) values ('Orga A', 'approved', '10665995600010') returning id`)).id;
const B = (await one(`insert into public.organizers (name, account_status) values ('Orga B', 'approved') returning id`)).id;
const P = (await one(`insert into public.organizers (name, account_status) values ('Orga en attente', 'pending') returning id`)).id;
await q(`insert into public.organizer_members (organizer_id, user_id, role) values ($1,$2,'owner'), ($3,$4,'owner'), ($5,$6,'owner')`, [A, USERS.staff.id, B, USERS.orgb.id, P, USERS.cust.id]);
const admin = await as(USERS.admin), ownA = await as(USERS.staff), ownB = await as(USERS.orgb), pend = await as(USERS.cust), plain = await as(USERS.cust2);
const day = new Date(Date.now() + 40 * 864e5).toISOString().slice(0, 10);
const body = (org, over = {}) => ({ org, mode: 'none', title: 'Soirée Test Wizard', event_type: 'Soirée', date: day, time: '22:00', venue_name: 'Salle Test', city: 'Pointe-à-Pitre', region: 'guadeloupe', visibility: 'public', ...over });
const count = async () => (await one(`select count(*)::int n from public.ticketed_events`)).n;

section('Création : rattachement vérifié côté serveur');
let r = await ownA.req('/api/organisateur/events', { method: 'POST', body: body(A) });
ok(r.status === 200 && r.data.slug === 'soiree-test-wizard', `création sur SON organisation → ${r.status} ${r.data?.slug}`);
const ev = await one(`select e.*, d.title from public.ticketed_events e join public.event_details d on d.ticketed_event_id = e.id where e.event_slug = 'soiree-test-wizard'`);
ok(ev.organizer_id === A && ev.status === 'draft' && ev.ticketing_mode === 'none' && ev.ticketing_enabled === false, 'brouillon rattaché à l’organisation choisie, billetterie non activée');
r = await ownA.req('/api/organisateur/events', { method: 'POST', body: body(B, { title: 'Vol sur B' }) });
ok(r.status === 403, `créer sur l’organisation d’un AUTRE → 403 (${r.status})`);
ok((await one(`select count(*)::int n from public.ticketed_events where organizer_id = $1`, [B])).n === 0, 'rien créé chez l’autre organisation');
r = await pend.req('/api/organisateur/events', { method: 'POST', body: body(P, { title: 'Chez attente' }) });
ok(r.status === 409 && /pas encore approuvée/.test(r.data.error), `organisation non approuvée refusée par le serveur : « ${r.data?.error} »`);
r = await admin.req('/api/organisateur/events', { method: 'POST', body: body(P, { title: 'Admin attente' }) });
ok(r.status === 409, `même un admin ne peut pas créer sur une organisation non approuvée (${r.status})`);
r = await admin.req('/api/organisateur/events', { method: 'POST', body: body(B, { title: 'Admin pour B' }) });
ok(r.status === 200, `admin crée pour n’importe quelle organisation approuvée (${r.status})`);
r = await plain.req('/api/organisateur/events', { method: 'POST', body: body(A, { title: 'Sans droits' }) });
ok(r.status === 403, `compte sans organisation → 403 (${r.status})`);
r = await ownA.req('/api/organisateur/events', { method: 'POST', body: body(A, { date: '2020-01-01', title: 'Date passée' }) });
ok(r.status === 400 && /passée/.test(r.data.error), `date passée refusée : « ${r.data?.error} »`);
r = await ownA.req('/api/organisateur/events', { method: 'POST', body: body(A) });
ok(r.status === 200 && r.data.slug !== 'soiree-test-wizard', `titre identique → adresse unique (${r.data?.slug})`);

section('Code d’intégration Bizouk : analysé, jamais stocké tel quel');
const before = await count();
for (const [name, code] of [['script', '<script>alert(document.cookie)</script>'], ['autre domaine', '<iframe src="https://evil.example/stores/reservation/place?event=1"></iframe>'], ['gestionnaire', '<iframe onload="x()" src="https://www.bizouk.com/stores/reservation/place?event=1"></iframe>'], ['vide', '']]) {
  r = await ownA.req('/api/organisateur/events', { method: 'POST', body: body(A, { mode: 'bizouk', bizouk_code: code, title: 'Bizouk ' + name }) });
  ok(r.status === 400 && r.data.field === 'bizouk_code', `code malveillant « ${name} » rejeté (${r.status}) : ${r.data?.error}`);
}
ok((await count()) === before, 'aucun évènement créé par les codes refusés');
const good = '<iframe style="background:red" src="https://www.bizouk.com/stores/reservation/place?event=128267&widget=1" name="x"></iframe><script src="https://static.bizouk.com/lib/js/widget/widget_client.js"></script>';
r = await ownA.req('/api/organisateur/events', { method: 'POST', body: body(A, { mode: 'bizouk', bizouk_code: good, title: 'Soirée Bizouk' }) });
ok(r.status === 200, `code Bizouk valide accepté (${r.status})`);
const bz = await one(`select e.ticketing_mode, e.bizouk_event_id, row_to_json(e)::text as e_json, row_to_json(d)::text as d_json from public.ticketed_events e join public.event_details d on d.ticketed_event_id = e.id where e.event_slug = 'soiree-bizouk'`);
ok(bz.ticketing_mode === 'bizouk' && bz.bizouk_event_id === '128267', 'seul l’identifiant 128267 est enregistré');
ok(!/<iframe|<script|background:|static\.bizouk|bizouk\.com/i.test(bz.e_json + bz.d_json), 'le code collé n’apparaît nulle part en base');
r = await ownA.req('/api/organisateur/events/soiree-bizouk/ticketing', { method: 'POST', body: { mode: 'bizouk', bizouk_code: '<script>1</script>' } });
ok(r.status === 400, `remplacement par un code malveillant refusé (${r.status})`);
r = await ownB.req('/api/organisateur/events/soiree-bizouk/ticketing', { method: 'POST', body: { mode: 'none' } });
ok(r.status === 403 || r.status === 404, `autre organisation ne peut pas changer le mode (${r.status})`);
r = await ownA.req('/api/organisateur/events/soiree-bizouk/ticketing', { method: 'POST', body: { mode: 'none' } });
ok(r.status === 200 && (await one(`select bizouk_event_id from public.ticketed_events where event_slug = 'soiree-bizouk'`)).bizouk_event_id === null, 'retrait du widget : identifiant supprimé');

section('Recherche d’organisation par référence : admin seulement');
const ref = (await one(`select reference from public.organizers where id = $1`, [A])).reference;
r = await ownA.req(`/api/organisateur/orgs?ref=${ref}`); ok(r.status === 403, `non-admin → 403 (${r.status})`);
r = await admin.req(`/api/organisateur/orgs?ref=${ref}`); ok(r.status === 200 && r.data.id === A && r.data.events >= 1, `admin retrouve l’organisation (${r.status})`);
r = await admin.req('/api/organisateur/orgs?ref=NOPE'); ok(r.status === 400, 'référence invalide → 400');

section('Inscription organisation (C) : en attente, pièces réservées aux admins');
const form = { data: { name: 'Asso Nouvelle', legal_form: 'association', siret: '', address: '1 rue des Fleurs', postal_code: '97100', city: 'Basse-Terre', responsible_first: 'Ada', responsible_last: 'Lovelace', contact_email: 'ada@example.com', phone: '0690123456', website: '', description: 'Association organisatrice de soirées.', regions: ['guadeloupe'], events_per_year: '1-3', accept_terms: true },
  docs: [{ kind: 'identity', path: 'orgdocs/aaaa1111.pdf', name: 'cni.pdf', size: 1000, mime: 'application/pdf' }, { kind: 'legal', path: 'orgdocs/bbbb2222.png', name: 'kbis.png', size: 900, mime: 'image/png' }] };
r = await new L.Client().req('/api/organisateur/inscription', { method: 'POST', body: form }); ok(r.status === 401, `sans connexion → 401 (${r.status})`);
r = await plain.req('/api/organisateur/inscription', { method: 'POST', body: { ...form, docs: [form.docs[0]] } }); ok(r.status === 400, `justificatif manquant → 400 (${r.data?.error})`);
r = await plain.req('/api/organisateur/inscription', { method: 'POST', body: { ...form, data: { ...form.data, siret: '12345678901234' } } }); ok(r.status === 400 && /SIRET/.test(r.data.error), `SIRET à clé fausse → 400 (${r.data?.error})`);
r = await plain.req('/api/organisateur/inscription', { method: 'POST', body: form });
ok(r.status === 200 && r.data.status === 'pending', `dossier envoyé (${r.status})`);
const newOrg = await one(`select o.*, m.role from public.organizers o join public.organizer_members m on m.organizer_id = o.id and m.user_id = $1 where o.name = 'Asso Nouvelle'`, [USERS.cust2.id]);
ok(newOrg.account_status === 'pending' && newOrg.role === 'owner' && !newOrg.reference, 'organisation en attente, auteur OWNER, sans référence');
r = await plain.req('/api/organisateur/events', { method: 'POST', body: body(newOrg.id, { title: 'Trop tôt' }) });
ok(r.status === 409, `tant qu’elle n’est pas approuvée : création refusée (${r.status})`);
const doc = (await one(`select id from public.organizer_documents where organizer_id = $1 and kind = 'identity'`, [newOrg.id])).id;
r = await plain.req(`/api/admin-gestion/org-document?id=${doc}`); ok(r.status === 403, `pièce : le propriétaire lui-même n’a pas accès (${r.status})`);
r = await new L.Client().req(`/api/admin-gestion/org-document?id=${doc}`); ok(r.status === 401, `pièce : anonyme refusé (${r.status})`);
r = await admin.req(`/api/admin-gestion/org-document?id=${doc}`); ok(r.status === 404, `pièce : admin autorisé (fichier absent du stockage de test → 404) (${r.status})`);
ok((await one(`select count(*)::int n from public.audit_log where action = 'organizer.document_view'`)).n === 1, 'consultation journalisée');
r = await admin.req(`/admin/gestion/organisateurs/${newOrg.id}?onglet=dossier`); ok(r.status === 200 && /Dossier d’inscription/.test(r.data) && /cni\.pdf/.test(r.data) && /Ada/.test(r.data), 'fiche admin : dossier et pièces affichés');
r = await plain.req('/devenir-organisateur'); ok(r.status === 200 && /Devenir organisateur/.test(r.data), 'page /devenir-organisateur accessible connecté');
r = await new L.Client().req('/devenir-organisateur'); ok(r.status === 307 || r.status === 308 || r.status === 302, `anonyme redirigé vers la connexion (${r.status})`);

section('Parcours navigateur (Playwright) : assistant en 3 étapes');
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
await ctx.addCookies(Object.entries(ownA.jar).map(([name, value]) => ({ name, value, url: L.BASE })));
const page = await ctx.newPage();
const errors = []; page.on('pageerror', (e) => errors.push(e.message));
const net = []; page.on('response', async (r) => { if (r.url().includes('/api/organisateur/events')) net.push(r.status() + ' ' + (await r.text().catch(() => ''))); });
await page.goto(L.BASE + '/organisateur/evenements/nouveau');
ok(await page.getByRole('heading', { name: 'Pour quelle organisation ?' }).isVisible(), 'étape 1 affichée');
ok(await page.getByText('Orga A').first().isVisible() && await page.getByText('+ Nouvelle organisation').isVisible(), 'cartes d’organisation + carte « Nouvelle organisation »');
ok(await page.locator('input[name=org]:checked').count() === 1, 'l’organisation courante est présélectionnée');
await page.getByText('Orga A').first().click();
await page.getByRole('button', { name: 'Continuer' }).click();
ok(await page.getByRole('heading', { name: 'Comment vends-tu tes billets ?' }).isVisible(), 'étape 2 : billetterie');
await page.getByRole('button', { name: 'Continuer' }).click();
ok(await page.getByText('Choisis une méthode de billetterie.').isVisible(), 'validation : méthode de billetterie obligatoire');
await page.locator('input[name=mode][value=bizouk]').check({ force: true });
await page.locator('#bizouk_code').fill('<script>alert(1)</script>');
await page.getByRole('button', { name: 'Continuer' }).click();
ok(await page.getByText(/Code refusé/).first().isVisible(), 'code malveillant : message clair, on reste sur l’étape');
await page.locator('#bizouk_code').fill('<iframe src="https://www.bizouk.com/stores/reservation/place?event=128267&widget=1"></iframe>');
ok(await page.getByText('Aperçu du widget').isVisible() && (await page.locator('iframe[title="Aperçu du widget Bizouk"]').getAttribute('sandbox')) !== null, 'aperçu du widget dans un iframe sandbox');
ok(await page.getByText(/n’apparaissent pas dans les statistiques internes/).isVisible(), 'avertissement : ventes Bizouk hors statistiques internes');
await page.getByRole('button', { name: 'Continuer' }).click();
ok(await page.getByRole('heading', { name: 'Les informations essentielles' }).isVisible(), 'étape 3 : informations');
await page.getByRole('button', { name: 'Créer le brouillon' }).click();
ok(await page.getByText('Le titre doit faire au moins 3 caractères.').isVisible() && await page.getByText('Choisis le type d’évènement.').isVisible(), 'validation champ par champ (français)');
await page.locator('#title').fill('Nuit Playwright');
await page.locator('#event_type').selectOption('Soirée');
await page.locator('#date').fill(day); await page.locator('#time').fill('21:30');
await page.locator('#venue_name').fill('Le Studio'); await page.locator('#city').fill('Le Gosier'); await page.locator('#region').selectOption('guadeloupe');
await page.screenshot({ path: process.env.OUT ? process.env.OUT + '/wizard-step3.png' : '/dev/null', fullPage: true }).catch(() => {});
await page.getByRole('button', { name: 'Créer le brouillon' }).click();
await page.waitForURL(/\/organisateur\/evenements\/nuit-playwright/, { timeout: 60000 });
await page.getByRole('heading', { name: 'Prochaines étapes' }).waitFor({ timeout: 30000 }).catch(() => {});
ok(await page.getByText('Évènement créé en brouillon').isVisible() && await page.getByRole('heading', { name: 'Prochaines étapes' }).isVisible(), 'arrivée sur le tableau de bord avec la checklist « Prochaines étapes »');
ok(await page.getByText('Vérifier le widget Bizouk').isVisible(), 'étape « widget Bizouk » dans la checklist');
const made = await one(`select e.ticketing_mode, e.bizouk_event_id, e.status, e.organizer_id from public.ticketed_events e where e.event_slug = 'nuit-playwright'`);
ok(made.status === 'draft' && made.bizouk_event_id === '128267' && made.organizer_id === A, 'évènement du navigateur : brouillon, Bizouk 128267, organisation A');
await page.goto(L.BASE + '/organisateur/evenements/nuit-playwright/billetterie');
await page.getByText('Aperçu du widget').first().waitFor({ timeout: 30000 }).catch(() => {});
ok(await page.getByText('Aperçu du widget').first().isVisible(), 'menu Billetterie : aperçu du widget et bouton de retrait');
await page.setViewportSize({ width: 390, height: 844 });
await page.goto(L.BASE + '/organisateur/evenements/nouveau');
ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'mobile : aucun défilement horizontal');
ok(errors.length === 0, `aucune erreur JavaScript (${errors.join(' | ')})`);
await Promise.race([browser.close(), new Promise((r) => setTimeout(r, 5000))]);
process.exit(L.summary('création d’évènement et inscription organisateur') ? 1 : 0);
