// s17 — publication d'un évènement créé en ligne : checklist, demande, doublon, file d'attente admin, refus avec motif, approbation,
// page publique /editions/<slug> (widget Bizouk régénéré), e-mails (uniquement vers l'adresse de test), évènement privé jamais servi.
import { chromium } from 'playwright';
import * as L from './lib.mjs';
const { ok, section, as, q, one, mailState, USERS } = L;

await L.resetDb();
await q(`truncate public.publication_requests, public.event_venues, public.organizer_documents, public.organizer_applications, public.organizer_members, public.event_sessions, public.event_details cascade`);
await q(`delete from public.organizers where not is_default`);
const A = (await one(`insert into public.organizers (name, account_status, stripe_ready) values ('Orga Pub', 'approved', false) returning id`)).id;
const P = (await one(`insert into public.organizers (name, account_status) values ('Orga attente', 'pending') returning id`)).id;
await q(`insert into public.organizer_members (organizer_id, user_id, role) values ($1,$2,'owner'), ($3,$4,'staff'), ($5,$6,'owner')`, [A, USERS.staff.id, A, USERS.cust.id, P, USERS.orgb.id]);
const admin = await as(USERS.admin), owner = await as(USERS.staff), crew = await as(USERS.cust), other = await as(USERS.orgb), anon = new L.Client();
const TEST_TO = 'mdn.productions170@gmail.com';
const day = new Date(Date.now() + 40 * 864e5).toISOString().slice(0, 10);
const make = (over) => ({ org: A, mode: 'bizouk', bizouk_code: '<iframe src="https://www.bizouk.com/stores/reservation/place?event=128267&widget=1"></iframe>', title: 'Nuit Pub', event_type: 'Soirée', date: day, time: '21:00', venue_name: 'Le Studio', city: 'Le Gosier', region: 'guadeloupe', visibility: 'public', ...over });
const sentSince = async (n) => (await mailState()).sent.slice(n);
const wait = async (n) => { for (let i = 0; i < 40 && (await mailState()).sent.length <= n; i++) await new Promise((r) => setTimeout(r, 150)); };
const flat = (m) => [].concat(m.to);

section('Création et checklist');
let r = await owner.req('/api/organisateur/events', { method: 'POST', body: make({}) });
ok(r.status === 200 && r.data.slug === 'nuit-pub', `évènement créé (${r.status})`);
r = await owner.req('/api/organisateur/events/nuit-pub/publication', { method: 'POST', body: { action: 'request' } });
ok(r.status === 409 && /checklist/i.test(r.data.error), `checklist incomplète : demande refusée « ${r.data?.error} »`);
r = await owner.req('/organisateur/evenements/nuit-pub?nouveau=1');
ok(r.status === 200 && /Demander la publication/.test(r.data) && /Description de l’évènement/.test(r.data) && /Visuel \(flyer ou vidéo\)/.test(r.data), 'tableau de bord : panneau « Publication » avec les points manquants');
const st = await one(`select d.description, d.flyer_url from public.event_details d join public.ticketed_events e on e.id = d.ticketed_event_id where e.event_slug = 'nuit-pub'`);
ok(!st.description && !st.flyer_url, 'description et visuel manquants au départ');

section('Visuel et description');
r = await owner.req('/api/organisateur/events/nuit-pub/visuel', { method: 'POST', body: { url: 'https://evil.example/x.jpg' } });
ok(r.status === 400, `visuel hors stockage refusé (${r.status})`);
r = await other.req('/api/organisateur/events/nuit-pub/visuel', { method: 'POST', body: { url: 'https://abc.public.blob.vercel-storage.com/evenements/nuit-pub/flyer.jpg' } });
ok(r.status === 403 || r.status === 404, `autre organisation : refusé (${r.status})`);
r = await owner.req('/api/organisateur/events/nuit-pub/visuel', { method: 'POST', body: { url: 'https://abc.public.blob.vercel-storage.com/evenements/nuit-pub/flyer.jpg' } });
ok(r.status === 200, `visuel enregistré (${r.status})`);
await q(`update public.event_details set description = $1 where ticketed_event_id = (select id from public.ticketed_events where event_slug = 'nuit-pub')`, ['Une nuit de fête avec <script>alert("xss")</script> DJ, ambiance et dresscode blanc.']);

section('Demande de publication');
let m0 = (await mailState()).sent.length;
r = await crew.req('/api/organisateur/events/nuit-pub/publication', { method: 'POST', body: { action: 'request' } });
ok(r.status === 403, `le staff ne peut pas demander la publication (${r.status})`);
r = await other.req('/api/organisateur/events/nuit-pub/publication', { method: 'POST', body: { action: 'request' } });
ok(r.status === 403 || r.status === 404, `une autre organisation ne peut pas non plus (${r.status})`);
r = await owner.req('/api/organisateur/events/nuit-pub/publication', { method: 'POST', body: { action: 'request' } });
ok(r.status === 200, `demande envoyée (${r.status} ${r.data?.error ?? ''})`);
r = await owner.req('/api/organisateur/events/nuit-pub/publication', { method: 'POST', body: { action: 'request' } });
ok(r.status === 409 && /déjà en attente/.test(r.data.error), `doublon refusé : « ${r.data?.error} »`);
await wait(m0);
let mails = await sentSince(m0);
ok(mails.length >= 1 && mails.every((m) => flat(m).length === 1 && flat(m)[0] === TEST_TO && /^\[TEST\]/.test(m.subject)), `e-mail de demande : uniquement ${TEST_TO} (${mails.map((m) => flat(m).join(',')).join(' | ')})`);
ok(/Nuit Pub/.test(mails[0]?.html ?? '') && /TEST : destinataires prévus/.test(mails[0]?.html ?? ''), 'l’e-mail de test indique les destinataires réels prévus');

section('File d’attente admin');
r = await owner.req('/admin/gestion/publications'); ok(r.status === 403, `un organisateur n’accède pas à la file (${r.status})`);
r = await admin.req('/admin/gestion/publications'); ok(r.status === 200 && /Publications à valider/.test(r.data) && /Nuit Pub/.test(r.data), 'la file affiche la demande');
const req1 = await one(`select id from public.publication_requests where status = 'pending'`);
r = await owner.req(`/api/admin-gestion/publications/${req1.id}`, { method: 'POST', body: { approve: true } }); ok(r.status === 403, `un organisateur ne peut pas valider (${r.status})`);
r = await anon.req(`/api/admin-gestion/publications/${req1.id}`, { method: 'POST', body: { approve: true } }); ok(r.status === 401, `anonyme refusé (${r.status})`);
r = await admin.req(`/api/admin-gestion/publications/${req1.id}`, { method: 'POST', body: { approve: false, reason: '' } });
ok(r.status === 400 && /motif/i.test(r.data.error), `refus sans motif rejeté : « ${r.data?.error} »`);
m0 = (await mailState()).sent.length;
r = await admin.req(`/api/admin-gestion/publications/${req1.id}`, { method: 'POST', body: { approve: false, reason: 'Le visuel est trop flou, merci de le remplacer.' } });
ok(r.status === 200, `refus avec motif (${r.status})`);
ok((await one(`select status from public.ticketed_events where event_slug = 'nuit-pub'`)).status === 'draft', 'l’évènement reste en brouillon');
r = await new L.Client().req('/editions/nuit-pub'); ok(r.status === 404, `page publique inexistante tant que non publié (${r.status})`);
await wait(m0); mails = await sentSince(m0);
ok(mails.length === 1 && flat(mails[0])[0] === TEST_TO && /refusée/.test(mails[0].subject) && /trop flou/.test(mails[0].html), 'e-mail de refus avec le motif (vers l’adresse de test seulement)');
r = await owner.req('/organisateur/evenements/nuit-pub'); ok(/Demande refusée/.test(r.data) && /trop flou/.test(r.data), 'l’organisateur voit le motif du refus');

section('Nouvelle demande puis approbation');
r = await owner.req('/api/organisateur/events/nuit-pub/publication', { method: 'POST', body: { action: 'request' } }); ok(r.status === 200, 'nouvelle demande après correction');
const req2 = await one(`select id from public.publication_requests where status = 'pending'`);
m0 = (await mailState()).sent.length;
r = await admin.req(`/api/admin-gestion/publications/${req2.id}`, { method: 'POST', body: { approve: true } }); ok(r.status === 200, `approbation (${r.status})`);
ok((await one(`select status, ticketing_enabled from public.ticketed_events where event_slug = 'nuit-pub'`)).status === 'published', 'évènement publié');
r = await admin.req(`/api/admin-gestion/publications/${req2.id}`, { method: 'POST', body: { approve: true } }); ok(r.status === 409, `demande déjà traitée (${r.status})`);
await wait(m0); mails = await sentSince(m0);
ok(mails.length === 1 && flat(mails[0])[0] === TEST_TO && /validée/.test(mails[0].subject), 'e-mail de validation (vers l’adresse de test seulement)');
let page = await new L.Client().req('/editions/nuit-pub');
ok(page.status === 200 && /Nuit Pub/.test(page.data), `page publique /editions/nuit-pub en ligne (${page.status})`);
ok(/stores\/reservation\/place\?event=128267/.test(page.data) && /sandbox=/.test(page.data), 'widget Bizouk régénéré (identifiant 128267) avec sandbox');
ok(!/<script>alert\("xss"\)/.test(page.data), 'aucun script injecté depuis la description');
ok(/flyer\.jpg/.test(page.data), 'visuel affiché');
r = await new L.Client().req('/sitemap.xml'); ok(/editions\/nuit-pub/.test(r.data), 'présent dans le sitemap');
r = await owner.req('/organisateur/evenements/nuit-pub'); ok(/Publié/.test(r.data), 'tableau de bord : évènement publié');

section('Garde-fous');
r = await owner.req('/api/organisateur/events', { method: 'POST', body: make({ title: 'Soirée privée', visibility: 'private', mode: 'none' }) });
const priv = r.data.slug;
await q(`update public.event_details set description = 'Soirée réservée aux invités, entrée sur liste.', flyer_url = 'https://abc.public.blob.vercel-storage.com/evenements/${priv}/f.jpg' where ticketed_event_id = (select id from public.ticketed_events where event_slug = $1)`, [priv]);
await owner.req(`/api/organisateur/events/${priv}/publication`, { method: 'POST', body: { action: 'request' } });
const req3 = await one(`select id from public.publication_requests where status = 'pending'`);
await admin.req(`/api/admin-gestion/publications/${req3.id}`, { method: 'POST', body: { approve: true } });
r = await new L.Client().req(`/editions/${priv}`); ok(r.status === 404, `évènement PRIVÉ publié : jamais servi publiquement (${r.status})`);
await q(`update public.organizers set account_status = 'suspended' where id = $1`, [A]);
await new Promise((x) => setTimeout(x, 1500));
r = await new L.Client().req('/editions/nuit-pub');
ok(r.status === 404 || /Nuit Pub/.test(r.data), `organisation suspendue : la page suit la règle SQL (${r.status})`);
await q(`update public.organizers set account_status = 'approved' where id = $1`, [A]);
const pendingOrg = await owner.req('/api/organisateur/events', { method: 'POST', body: make({ org: P, title: 'Chez attente' }) });
ok(pendingOrg.status === 403 || pendingOrg.status === 409, `organisation en attente : création refusée (${pendingOrg.status})`);

section('Interface admin (Playwright)');
r = await owner.req('/api/organisateur/events', { method: 'POST', body: make({ title: 'Nuit Refus', mode: 'none' }) });
await q(`update public.event_details set description = 'Description suffisante pour la checklist de cet évènement.', flyer_url = 'https://abc.public.blob.vercel-storage.com/evenements/nuit-refus/f.jpg' where ticketed_event_id = (select id from public.ticketed_events where event_slug = 'nuit-refus')`);
await owner.req('/api/organisateur/events/nuit-refus/publication', { method: 'POST', body: { action: 'request' } });
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
await ctx.addCookies(Object.entries(admin.jar).map(([name, value]) => ({ name, value, url: L.BASE })));
const pg = await ctx.newPage(); const errs = []; pg.on('pageerror', (e) => errs.push(e.message));
await pg.goto(L.BASE + '/admin/gestion/publications');
await pg.getByRole('button', { name: 'Examiner' }).first().click();
ok(await pg.getByText('Description de l’évènement').first().isVisible(), 'aperçu de la checklist dans la file');
await pg.locator('#org-main').getByRole('button', { name: 'Refuser' }).click();
ok(await pg.getByText('Le motif du refus est obligatoire (5 caractères minimum).').isVisible(), 'refus sans motif : message clair');
await pg.getByLabel(/Motif/).fill('Ce n’est pas un évènement conforme.');
await pg.locator('#org-main').getByRole('button', { name: 'Refuser' }).click();
await pg.waitForFunction(() => !document.body.innerText.includes('Nuit Refus'), null, { timeout: 15000 }).catch(() => {});
ok((await one(`select status from public.publication_requests where reason like 'Ce n’est pas%'`))?.status === 'rejected', 'refus enregistré depuis l’interface');
await pg.goto(L.BASE + '/admin');
ok(await pg.getByText('Publications à valider').first().isVisible(), 'tableau de bord admin : carte « Publications à valider »');
ok(errs.length === 0, `aucune erreur JavaScript (${errs.join(' | ')})`);
await Promise.race([browser.close(), new Promise((x) => setTimeout(x, 5000))]);
process.exit(L.summary('publication d’un évènement créé en ligne') ? 1 : 0);
